config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bouni.zsh-theme:
    src: oh-my-zsh/themes/bouni.zsh-theme
    dst: ~/.oh-my-zsh/themes/bouni.zsh-theme
  f_config:
    src: config/termite/config
    dst: ~/.config/termite/config
  f_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  d_scripts:
    src: config/i3/scripts
    dst: ~/.config/i3/scripts
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
profiles:
  archlinux:
    dotfiles:
    - f_zshrc
    - f_bouni.zsh-theme
    - f_config
    - f_i3_config
    - d_scripts
    - d_dunst
    - d_polybar
    - f_config.rasi
  horus:
    dotfiles:
    - f_zshrc
    - f_bouni.zsh-theme
    - f_init.vim
